import { TestBed } from '@angular/core/testing';
import { provideZonelessChangeDetection, signal } from '@angular/core';
import type { TelemetryLog } from './telemetry-worker.service';
import { TelemetryWorkerService } from './telemetry-worker.service';

// The real service constructs a `Worker` via `import.meta.url`, which neither
// jsdom nor Jest's CommonJS runtime can load. Stub it and drive the dataset by
// hand so the filtering/KPI logic is tested in isolation.
jest.mock('./telemetry-worker.service', () => ({
  TelemetryWorkerService: class {
    readonly pendingCount = signal<number | null>(null);
    generate = jest.fn();
    ngOnDestroy = jest.fn();
  },
}));

// Imported after the mock so the component picks up the stubbed class.
import { VirtualScrollDemoPage } from './virtual-scroll-demo';

function makeLog(overrides: Partial<TelemetryLog> = {}): TelemetryLog {
  return {
    id: 1,
    timestamp: new Date('2026-01-01T00:00:00.000Z'),
    service: 'auth-service',
    level: 'INFO',
    message: 'HTTP-Anfrage erfolgreich verarbeitet',
    latencyMs: 50,
    statusCode: 200,
    ...overrides,
  };
}

const SAMPLE_LOGS: TelemetryLog[] = [
  makeLog({
    id: 1,
    service: 'auth-service',
    level: 'INFO',
    message: 'Cache-Treffer',
    latencyMs: 20,
  }),
  makeLog({
    id: 2,
    service: 'payment-gateway',
    level: 'ERROR',
    message: 'Verbindungsfehler',
    latencyMs: 900,
  }),
  makeLog({
    id: 3,
    service: 'edge-worker',
    level: 'WARN',
    message: 'SLA überschritten',
    latencyMs: 300,
  }),
  makeLog({
    id: 4,
    service: 'auth-service',
    level: 'DEBUG',
    message: 'JWT-Token erneuert',
    latencyMs: 60,
  }),
];

describe('VirtualScrollDemoPage', () => {
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [VirtualScrollDemoPage],
      // The mocked class is a plain class without `providedIn: 'root'`,
      // so it has to be provided explicitly.
      providers: [provideZonelessChangeDetection(), TelemetryWorkerService],
    }).compileComponents();
  });

  function create(): VirtualScrollDemoPage {
    const fixture = TestBed.createComponent(VirtualScrollDemoPage);
    fixture.detectChanges();
    return fixture.componentInstance;
  }

  /** Replaces the dataset generated by the (stubbed) worker. */
  function seed(component: VirtualScrollDemoPage, logs: TelemetryLog[]): void {
    component.allLogs.set(logs);
    component.totalItemsCount.set(logs.length);
  }

  it('should create the component', () => {
    expect(create()).toBeTruthy();
  });

  it('should start with an empty dataset and expose the item size', () => {
    const component = create();
    expect(component.allLogs()).toEqual([]);
    expect(component.itemSize).toBe(64);
  });

  it('should filter logs by level', () => {
    const component = create();
    seed(component, SAMPLE_LOGS);

    component.selectedLevel.set('ERROR');
    expect(component.filteredLogs().map((l) => l.id)).toEqual([2]);
  });

  it('should filter logs by search query across message, service and id', () => {
    const component = create();
    seed(component, SAMPLE_LOGS);

    component.searchQuery.set('auth-service');
    expect(component.filteredLogs().map((l) => l.id)).toEqual([1, 4]);

    component.searchQuery.set('2');
    // "2" matches the service name of row 2 and nothing else.
    expect(component.filteredLogs().every((l) => l.level === 'ERROR')).toBe(true);
  });

  it('should combine level and query filters', () => {
    const component = create();
    seed(component, SAMPLE_LOGS);

    component.selectedLevel.set('DEBUG');
    component.searchQuery.set('auth-service');

    expect(component.filteredLogs().map((l) => l.id)).toEqual([4]);
  });

  it('should compute error count and average latency over the filtered set', () => {
    const component = create();
    seed(component, SAMPLE_LOGS);

    expect(component.errorLogsCount()).toBe(1);
    // (20 + 900 + 300 + 60) / 4
    expect(component.avgLatency()).toBe(320);

    component.selectedLevel.set('ERROR');
    expect(component.errorLogsCount()).toBe(1);
    expect(component.avgLatency()).toBe(900);
  });

  it('should report a near-total DOM reduction for a large dataset', () => {
    const component = create();
    const many = Array.from({ length: 5_000 }, (_, i) => makeLog({ id: i + 1 }));
    seed(component, many);

    // ~14 DOM nodes rendered out of 5 000 rows.
    expect(Number(component.domReductionPercent())).toBeGreaterThan(99);
  });

  it('should clamp the DOM reduction to zero when the dataset is tiny', () => {
    const component = create();
    seed(component, SAMPLE_LOGS);

    // Four rows all fit in the viewport, so there is no reduction to report —
    // and it must never be displayed as a negative percentage.
    expect(Number(component.domReductionPercent())).toBe(0);
  });

  it('should map every level to a CSS class', () => {
    const component = create();
    expect(component.getLevelClass('ERROR')).toBe('level-error');
    expect(component.getLevelClass('WARN')).toBe('level-warn');
    expect(component.getLevelClass('INFO')).toBe('level-info');
    expect(component.getLevelClass('DEBUG')).toBe('level-debug');
  });

  it('should use the log id as trackBy key', () => {
    const component = create();
    expect(component.trackById(5, makeLog({ id: 42 }))).toBe(42);
  });

  it('should ask the worker service to generate a new dataset', async () => {
    const component = create();
    const service = TestBed.inject(TelemetryWorkerService) as unknown as {
      generate: jest.Mock;
    };

    service.generate.mockResolvedValue({ items: SAMPLE_LOGS, durationMs: 12.5 });

    component.setDatasetSize(4);
    await Promise.resolve();
    await Promise.resolve();

    expect(service.generate).toHaveBeenCalledWith(4);
    expect(component.allLogs().length).toBe(4);
    expect(component.totalItemsCount()).toBe(4);
    expect(component.lastGenerationMs()).toBe(12.5);
  });
});
